import { collectAudioFingerprint } from '../collectors/audio.js';import { collectCanvasFingerprint } from '../collectors/canvas.js';import { collectCssMediaFingerprint } from '../collectors/cssMedia.js';import { collectFeatureDetectionFingerprint } from '../collectors/featureDetection.js';import { collectFontsFingerprint } from '../collectors/fonts.js';import { collectGamepadFingerprint } from '../collectors/gamepad.js';import { collectNavigatorFingerprint } from '../collectors/navigator.js';import { collectNetworkFingerprint } from '../collectors/network.js';import { collectPermissionsFingerprint } from '../collectors/permissions.js';import { collectScreenFingerprint } from '../collectors/screen.js';import { collectWebGLFingerprint } from '../collectors/webgl.js';import { collectWebGPUFingerprint } from '../collectors/webgpu.js';import { collectWebXRFingerprint } from '../collectors/webxr.js';import { collectStorageFingerprint } from '../collectors/storage.js';import { collectWindowFingerprint } from '../collectors/window.js';
import { collectAccessibilityPreferencesFingerprint } from '../collectors/accessibilityPreferences.js';
import { collectAccessibilityEnvironmentFingerprint } from '../collectors/accessibilityEnvironment.js';
import { collectAccessibilityAPISurfaceFingerprint } from '../collectors/accessibilityAPISurface.js';
import { DEFAULT_EXTENSION_ARTIFACT_DURATION_MS, observeAccessibilityExtensionArtifacts } from '../collectors/accessibilityExtensionArtifacts.js';
import { copyFingerprintJson, copySummary, downloadFingerprintJson, downloadJson, fingerprintFilename, selectExport } from '../export/jsonExport.js';
import { renderComparison, renderDataRows, renderFilteredRows, renderFingerprint, renderStatus, updateProgress } from '../ui/renderer.js';
import { buildFingerprint, buildResearchRecord } from '../ui/summary.js';
import { compareFingerprints, createComparisonReport, validateFingerprintJson } from '../ui/comparison.js';
import { initializeExperimentPanel } from '../ui/experimentPanel.js';

const $ = (id) => document.querySelector(id); const elements = {
 collectButton:$('#collect-button'), recollectButton:$('#recollect-button'), clearPassiveButton:$('#clear-passive-button'), clearSessionButton:$('#clear-session-button'), copyButton:$('#copy-button'), copySummaryButton:$('#copy-summary-button'), downloadButton:$('#download-button'), downloadSummaryButton:$('#download-summary-button'), importInput:$('#import-input'), debugToggle:$('#debug-toggle'), statusMessage:$('#status-message'), progress:$('#progress'), currentCollector:$('#current-collector'), completedCount:$('#completed-count'), warningCount:$('#warning-count'), errorCount:$('#error-count'), completedAt:$('#completed-at'), summaryCards:$('#summary-cards'), categoryNav:$('#category-nav'), structuredToggle:$('#structured-toggle'), rawToggle:$('#raw-toggle'), searchInput:$('#search-input'), filterSelect:$('#filter-select'), clearFilters:$('#clear-filters'), filterCount:$('#filter-count'), structuredView:$('#structured-view'), jsonViewer:$('#json-viewer'), includeVolatile:$('#include-volatile'), showIdentical:$('#show-identical'), onlyDifferences:$('#only-differences'), comparisonSummary:$('#comparison-summary'), comparisonTable:$('#comparison-table'), downloadComparisonButton:$('#download-comparison-button'), copyFeedback:$('#copy-feedback'), artifactPanel:$('#extension-artifacts-panel'), observeArtifactsButton:$('#observe-artifacts-button'), artifactStatus:$('#artifact-status'), artifactProgress:$('#artifact-progress'), artifactRemaining:$('#artifact-remaining'), artifactDuration:$('#artifact-duration'), artifactMutations:$('#artifact-mutations'), artifactAria:$('#artifact-aria'), artifactInjected:$('#artifact-injected'), artifactGlobals:$('#artifact-globals'), artifactDisconnected:$('#artifact-disconnected') };
const collectors = [['navigator',collectNavigatorFingerprint],['screen',collectScreenFingerprint],['window',collectWindowFingerprint],['canvas',collectCanvasFingerprint],['webgl',collectWebGLFingerprint],['audio',collectAudioFingerprint],['webgpu',collectWebGPUFingerprint],['webxr',collectWebXRFingerprint],['permissions',collectPermissionsFingerprint],['storage',collectStorageFingerprint],['network',collectNetworkFingerprint],['fonts',collectFontsFingerprint],['cssMedia',collectCssMediaFingerprint],['featureDetection',collectFeatureDetectionFingerprint],['gamepad',collectGamepadFingerprint],['accessibilityPreferences',collectAccessibilityPreferencesFingerprint],['accessibilityEnvironment',collectAccessibilityEnvironmentFingerprint],['accessibilityAPISurface',collectAccessibilityAPISurfaceFingerprint]];
let latestFingerprint=null, importedFingerprint=null, importedFilename=null, comparisonA=null, comparisonB=null, latestComparison=null, isCollecting=false, changedPaths=new Set(), extensionArtifactObservation=null, interactionExperiment=null, activeResultView='passive', sessionBase=buildResearchRecord();
const currentRecord=()=>buildResearchRecord({passiveRecord:latestFingerprint||sessionBase,extensionArtifactObservation,interactionExperiment});
const viewPayload=()=>({passive:currentRecord().passiveSnapshot,extension:currentRecord().extensionArtifactObservation,interaction:currentRecord().interactionExperiment,complete:currentRecord()})[activeResultView];
function renderActiveResult(){const payload=viewPayload(),performed=activeResultView==='complete'||payload?.performed;document.querySelector('#active-result-heading').textContent=({passive:'Passive Snapshot',extension:'Extension Artifact Observation',interaction:'Interaction Experiment',complete:'Complete Research Record'})[activeResultView];document.querySelectorAll('.result-tab').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.resultView===activeResultView)));elements.jsonViewer.textContent=performed?JSON.stringify(payload,null,2):'Not performed';if(elements.structuredView.hidden===false){if(activeResultView==='passive'&&latestFingerprint)renderFilteredRows(latestFingerprint,elements,{search:elements.searchInput.value,filter:elements.filterSelect.value,changedPaths});else renderDataRows(performed?{...payload,performed:true}:{performed:false},elements.structuredView,elements.searchInput.value);}if(activeResultView!=='passive')elements.filterCount.textContent=performed?'Current view':'Not performed';}
async function collectFingerprint(){ if(isCollecting) return; isCollecting=true; elements.collectButton.disabled=true; elements.recollectButton.disabled=true; const startedAt=new Date(); const results={}; let completed=0,warnings=0,errors=0; updateProgress(elements,{total:collectors.length}); for(const [name,collector] of collectors){ updateProgress(elements,{current:name,completed,total:collectors.length,warnings,errors}); results[name]=await runCollector(name,collector, elements.debugToggle.checked); completed++; warnings+=(results[name].warnings||[]).length; errors+=(results[name].errors||[]).length; updateProgress(elements,{current:name,completed,total:collectors.length,warnings,errors}); await new Promise(requestAnimationFrame); } latestFingerprint=buildFingerprint({collectorResults:results,startedAt,endedAt:new Date(),debugMode:elements.debugToggle.checked,extensionArtifactObservation,interactionExperiment}); renderFingerprint(latestFingerprint,elements,{search:elements.searchInput.value,filter:elements.filterSelect.value,changedPaths}); renderActiveResult(); document.querySelector('#overview-passive').textContent='Collected'; isCollecting=false; elements.collectButton.disabled=false; elements.recollectButton.disabled=false; maybeCompare(); }
async function runCollector(name,collector,debugMode){ const start=performance.now(); try{ const result=await withTimeout(Promise.resolve().then(collector),10000,name); return {...result,durationMs:Math.round(performance.now()-start)}; }catch(error){ return {category:name,supported:false,values:{},warnings:[],errors:[{collector:name,message:error.message||String(error),type:error.name||'CollectorError',stage:error.name==='TimeoutError'?'timeout':'collection',continued:true,stack:debugMode?error.stack:undefined}],durationMs:Math.round(performance.now()-start),timedOut:error.name==='TimeoutError'}; } }
function withTimeout(promise,ms,name){ return new Promise((resolve,reject)=>{ const id=setTimeout(()=>{const e=new Error(`${name} collector timed out after ${ms} ms`); e.name='TimeoutError'; reject(e);},ms); promise.then((v)=>{clearTimeout(id);resolve(v);},(e)=>{clearTimeout(id);reject(e);}); }); }
function maybeCompare(){ const a=comparisonA||latestFingerprint,b=comparisonB||importedFingerprint;if(!a||!b)return;latestComparison=compareFingerprints(a,b,{includeVolatile:elements.includeVolatile.checked,family:document.querySelector('#comparison-family')?.value||'all'}); changedPaths=new Set(latestComparison.rows.filter(r=>['changed','only in current','only in imported'].includes(r.result)).map(r=>r.path)); renderComparison(latestComparison,elements,{showIdentical:elements.showIdentical.checked,onlyDifferences:elements.onlyDifferences.checked});renderActiveResult(); }

async function observeArtifacts(){
  elements.observeArtifactsButton.disabled=true; elements.artifactStatus.textContent='Observation Running'; elements.artifactDisconnected.textContent='No'; elements.artifactProgress.max=DEFAULT_EXTENSION_ARTIFACT_DURATION_MS;
  const started=performance.now(); const interval=setInterval(()=>{const elapsed=Math.min(DEFAULT_EXTENSION_ARTIFACT_DURATION_MS,performance.now()-started);elements.artifactProgress.value=elapsed;elements.artifactRemaining.textContent=`${Math.max(0,Math.ceil(DEFAULT_EXTENSION_ARTIFACT_DURATION_MS-elapsed))} ms remaining`;},50);
  const result=await observeAccessibilityExtensionArtifacts({ignoredRoot:elements.artifactPanel}); clearInterval(interval); const v=result.values;
  extensionArtifactObservation={performed:true,supported:result.supported,timing:{startedAt:v.observationStartedAt,finishedAt:v.observationFinishedAt,durationMs:v.observationDurationMs,configuredDurationMs:v.configuredDurationMs},observerDisconnected:v.observerDisconnected,aggregateFeatures:v,warnings:result.warnings||[],errors:result.errors||[]};
  elements.artifactProgress.value=DEFAULT_EXTENSION_ARTIFACT_DURATION_MS; elements.artifactStatus.textContent=result.supported?'Observation Stopped — Completed':'Observation Stopped — Unsupported'; document.querySelector('#overview-extension').textContent=result.supported?'Completed':'Completed (Unsupported)'; elements.artifactRemaining.textContent='0 ms remaining'; elements.artifactDuration.textContent=`${v.observationDurationMs} ms`; elements.artifactMutations.textContent=v.mutations.totalMutationCount; elements.artifactAria.textContent=v.accessibilityMutations.ariaMutationCount;
  elements.artifactInjected.textContent=v.injectedElements.styleElementCount+v.injectedElements.scriptElementCount+v.injectedElements.stylesheetLinkCount; elements.artifactGlobals.textContent=v.globalSurface.newGlobalPropertyNames.length; elements.artifactDisconnected.textContent=v.observerDisconnected?'Yes':'No'; elements.observeArtifactsButton.disabled=false;
  ['#view-artifact-data','#copy-artifact-json','#download-artifact-json','#clear-artifact-result'].forEach(s=>document.querySelector(s).hidden=false);renderDataRows(extensionArtifactObservation,document.querySelector('#artifact-data-viewer'));renderActiveResult();maybeCompare();
}
elements.observeArtifactsButton.addEventListener('click',observeArtifacts);

elements.collectButton.addEventListener('click',collectFingerprint); elements.recollectButton.addEventListener('click',collectFingerprint);
function clearPassive(){latestFingerprint=null;document.querySelector('#overview-passive').textContent='Not Collected';elements.summaryCards.innerHTML='';elements.categoryNav.innerHTML='';[elements.copyButton,elements.copySummaryButton,elements.downloadButton,elements.downloadSummaryButton].forEach(b=>b.disabled=true);renderActiveResult();renderStatus('Passive snapshot cleared. Extension and interaction results were retained.',elements);}
function clearArtifact(){extensionArtifactObservation=null;document.querySelector('#overview-extension').textContent='Not Performed';elements.artifactStatus.textContent='Not Observed';elements.artifactProgress.value=0;elements.artifactRemaining.textContent='Not running';elements.artifactDuration.textContent=elements.artifactMutations.textContent=elements.artifactAria.textContent=elements.artifactInjected.textContent=elements.artifactGlobals.textContent='—';elements.artifactDisconnected.textContent='No';document.querySelector('#artifact-data-viewer').hidden=true;['#view-artifact-data','#copy-artifact-json','#download-artifact-json','#clear-artifact-result'].forEach(s=>document.querySelector(s).hidden=true);renderActiveResult();}
function clearInteraction(){interactionExperiment=null;document.querySelector('#overview-interaction').textContent='Not Performed';document.querySelector('#interaction-results').hidden=true;renderActiveResult();}
elements.clearPassiveButton.addEventListener('click',clearPassive);elements.clearSessionButton.addEventListener('click',()=>{clearPassive();clearArtifact();clearInteraction();sessionBase=buildResearchRecord();renderStatus('Complete page session cleared: passive, extension, and interaction results removed.',elements);});
elements.copyButton.addEventListener('click',()=>action(()=>copyFingerprintJson(latestFingerprint),'Copied JSON.')); elements.copySummaryButton.addEventListener('click',()=>action(()=>copySummary(latestFingerprint),'Copied summary.')); elements.downloadButton.addEventListener('click',()=>latestFingerprint&&downloadFingerprintJson(latestFingerprint)); elements.downloadSummaryButton.addEventListener('click',()=>latestFingerprint&&downloadFingerprintJson(latestFingerprint,'summary'));
elements.importInput.addEventListener('change',async(e)=>{ const file=e.target.files?.[0]; if(!file) return; try{ importedFilename=file.name; importedFingerprint=JSON.parse(await file.text()); validateFingerprintJson(importedFingerprint); renderStatus(`Imported ${file.name} locally for comparison.`,elements); maybeCompare(); }catch(err){ importedFingerprint=null; renderStatus(`Import failed: ${err.message}`,elements); }});
[elements.includeVolatile,elements.showIdentical,elements.onlyDifferences].forEach(el=>el.addEventListener('change',maybeCompare)); elements.downloadComparisonButton.addEventListener('click',()=>{ if(latestComparison) downloadJson(createComparisonReport(latestComparison,{current:'current fingerprint',imported:importedFilename}),`comparison-report_${new Date().toISOString()}.json`,'comparison'); });
[elements.searchInput,elements.filterSelect].forEach(el=>el.addEventListener('input',()=>renderActiveResult())); elements.clearFilters.addEventListener('click',()=>{elements.searchInput.value='';elements.filterSelect.value='all';renderActiveResult();});
elements.structuredToggle.addEventListener('click',()=>{elements.structuredView.hidden=false;elements.jsonViewer.hidden=true;}); elements.rawToggle.addEventListener('click',()=>{elements.structuredView.hidden=true;elements.jsonViewer.hidden=false;});
async function action(fn,msg){ try{ await fn(); elements.copyFeedback.textContent=msg; }catch(e){ elements.copyFeedback.textContent=`Action failed: ${e.message}`; } }

document.querySelectorAll('.result-tab').forEach(button=>button.addEventListener('click',()=>{activeResultView=button.dataset.resultView;renderActiveResult();}));
document.querySelector('#copy-view-json').addEventListener('click',()=>action(()=>copyFingerprintJson(viewPayload()),'Copied current results view JSON.'));
document.querySelector('#download-view-json').addEventListener('click',()=>downloadJson(viewPayload(),`${activeResultView}_${fingerprintFilename(currentRecord())}`));
document.querySelector('#view-artifact-data').addEventListener('click',()=>{const v=document.querySelector('#artifact-data-viewer');v.hidden=!v.hidden;renderDataRows(extensionArtifactObservation,v);});
document.querySelector('#copy-artifact-json').addEventListener('click',()=>action(()=>copyFingerprintJson(extensionArtifactObservation),'Copied Extension Artifact JSON.'));
document.querySelector('#download-artifact-json').addEventListener('click',()=>downloadJson(extensionArtifactObservation,`extension-artifact_${fingerprintFilename(currentRecord())}`));
document.querySelector('#clear-artifact-result').addEventListener('click',()=>{clearArtifact();renderStatus('Extension observation cleared. Other measurements were retained.',elements);});

initializeExperimentPanel(document.querySelector('#interaction-experiment-panel'),{onState(state){const el=document.querySelector('#overview-interaction');if(el)el.textContent=state;},onResult(result){if(!result.performed)return;interactionExperiment=result;const section=document.querySelector('#interaction-results');section.hidden=false;renderDataRows(result,document.querySelector('#interaction-data-viewer'));renderActiveResult();maybeCompare();}});
document.querySelector('#view-interaction-data').addEventListener('click',()=>{const v=document.querySelector('#interaction-data-viewer');v.hidden=!v.hidden;renderDataRows(interactionExperiment,v);});
document.querySelector('#copy-interaction-json').addEventListener('click',()=>action(()=>copyFingerprintJson(interactionExperiment),'Copied Interaction Experiment JSON.'));
document.querySelector('#download-interaction-json').addEventListener('click',()=>downloadJson(interactionExperiment,`interaction-experiment_${fingerprintFilename(currentRecord())}`));
document.querySelector('#clear-interaction-result').addEventListener('click',()=>{clearInteraction();renderStatus('Interaction experiment result cleared. Other measurements were retained.',elements);});

const exportSelected=document.querySelector('#export-selected'); if(exportSelected) exportSelected.addEventListener('click',()=>{const record=currentRecord(),type=document.querySelector('#export-type').value;downloadJson(selectExport(record,type),`${type}_${fingerprintFilename(record)}`);});

for(const [selector,slot] of [['#compare-a','a'],['#compare-b','b']]) document.querySelector(selector)?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text());validateFingerprintJson(value);if(slot==='a')comparisonA=value;else comparisonB=value;if(comparisonA&&comparisonB){importedFingerprint=comparisonB;latestComparison=compareFingerprints(comparisonA,comparisonB,{includeVolatile:elements.includeVolatile.checked,family:document.querySelector('#comparison-family').value});renderComparison(latestComparison,elements,{showIdentical:elements.showIdentical.checked,onlyDifferences:elements.onlyDifferences.checked});}}catch(error){renderStatus(`Local import failed: ${error.message}`,elements);}});
document.querySelector('#comparison-family')?.addEventListener('change',()=>{if(comparisonA&&comparisonB){latestComparison=compareFingerprints(comparisonA,comparisonB,{includeVolatile:elements.includeVolatile.checked,family:document.querySelector('#comparison-family').value});renderComparison(latestComparison,elements,{showIdentical:elements.showIdentical.checked,onlyDifferences:elements.onlyDifferences.checked});}else maybeCompare();});
renderActiveResult();
