import { collectAudioFingerprint } from '../collectors/audio.js';import { collectCanvasFingerprint } from '../collectors/canvas.js';import { collectCssMediaFingerprint } from '../collectors/cssMedia.js';import { collectFeatureDetectionFingerprint } from '../collectors/featureDetection.js';import { collectFontsFingerprint } from '../collectors/fonts.js';import { collectGamepadFingerprint } from '../collectors/gamepad.js';import { collectNavigatorFingerprint } from '../collectors/navigator.js';import { collectNetworkFingerprint } from '../collectors/network.js';import { collectPermissionsFingerprint } from '../collectors/permissions.js';import { collectScreenFingerprint } from '../collectors/screen.js';import { collectWebGLFingerprint } from '../collectors/webgl.js';import { collectWebGPUFingerprint } from '../collectors/webgpu.js';import { collectWebXRFingerprint } from '../collectors/webxr.js';import { collectStorageFingerprint } from '../collectors/storage.js';import { collectWindowFingerprint } from '../collectors/window.js';
import { collectAccessibilityPreferencesFingerprint } from '../collectors/accessibilityPreferences.js';
import { collectAccessibilityEnvironmentFingerprint } from '../collectors/accessibilityEnvironment.js';
import { collectAccessibilityAPISurfaceFingerprint } from '../collectors/accessibilityAPISurface.js';
import { DEFAULT_EXTENSION_ARTIFACT_DURATION_MS, observeAccessibilityExtensionArtifacts } from '../collectors/accessibilityExtensionArtifacts.js';
import { copyFingerprintJson, copySummary, downloadFingerprintJson, downloadJson } from '../export/jsonExport.js';
import { renderComparison, renderFilteredRows, renderFingerprint, renderStatus, updateProgress } from '../ui/renderer.js';
import { buildFingerprint } from '../ui/summary.js';
import { compareFingerprints, createComparisonReport, validateFingerprintJson } from '../ui/comparison.js';
import { initializeExperimentPanel } from '../ui/experimentPanel.js';

const $ = (id) => document.querySelector(id); const elements = {
 collectButton:$('#collect-button'), recollectButton:$('#recollect-button'), clearButton:$('#clear-button'), copyButton:$('#copy-button'), copySummaryButton:$('#copy-summary-button'), downloadButton:$('#download-button'), downloadSummaryButton:$('#download-summary-button'), importInput:$('#import-input'), debugToggle:$('#debug-toggle'), statusMessage:$('#status-message'), progress:$('#progress'), currentCollector:$('#current-collector'), completedCount:$('#completed-count'), warningCount:$('#warning-count'), errorCount:$('#error-count'), completedAt:$('#completed-at'), summaryCards:$('#summary-cards'), categoryNav:$('#category-nav'), structuredToggle:$('#structured-toggle'), rawToggle:$('#raw-toggle'), searchInput:$('#search-input'), filterSelect:$('#filter-select'), clearFilters:$('#clear-filters'), filterCount:$('#filter-count'), structuredView:$('#structured-view'), jsonViewer:$('#json-viewer'), includeVolatile:$('#include-volatile'), showIdentical:$('#show-identical'), onlyDifferences:$('#only-differences'), comparisonSummary:$('#comparison-summary'), comparisonTable:$('#comparison-table'), downloadComparisonButton:$('#download-comparison-button'), copyFeedback:$('#copy-feedback'), artifactPanel:$('#extension-artifacts-panel'), observeArtifactsButton:$('#observe-artifacts-button'), artifactStatus:$('#artifact-status'), artifactProgress:$('#artifact-progress'), artifactRemaining:$('#artifact-remaining'), artifactDuration:$('#artifact-duration'), artifactMutations:$('#artifact-mutations'), artifactAria:$('#artifact-aria'), artifactInjected:$('#artifact-injected'), artifactGlobals:$('#artifact-globals'), artifactDisconnected:$('#artifact-disconnected') };
const collectors = [['navigator',collectNavigatorFingerprint],['screen',collectScreenFingerprint],['window',collectWindowFingerprint],['canvas',collectCanvasFingerprint],['webgl',collectWebGLFingerprint],['audio',collectAudioFingerprint],['webgpu',collectWebGPUFingerprint],['webxr',collectWebXRFingerprint],['permissions',collectPermissionsFingerprint],['storage',collectStorageFingerprint],['network',collectNetworkFingerprint],['fonts',collectFontsFingerprint],['cssMedia',collectCssMediaFingerprint],['featureDetection',collectFeatureDetectionFingerprint],['gamepad',collectGamepadFingerprint],['accessibilityPreferences',collectAccessibilityPreferencesFingerprint],['accessibilityEnvironment',collectAccessibilityEnvironmentFingerprint],['accessibilityAPISurface',collectAccessibilityAPISurfaceFingerprint]];
let latestFingerprint=null, importedFingerprint=null, importedFilename=null, latestComparison=null, isCollecting=false, changedPaths=new Set(), extensionArtifactObservation=null, interactionExperiment={performed:false};
async function collectFingerprint(){ if(isCollecting) return; isCollecting=true; elements.collectButton.disabled=true; elements.recollectButton.disabled=true; const startedAt=new Date(); const results={}; let completed=0,warnings=0,errors=0; updateProgress(elements,{total:collectors.length}); for(const [name,collector] of collectors){ updateProgress(elements,{current:name,completed,total:collectors.length,warnings,errors}); results[name]=await runCollector(name,collector, elements.debugToggle.checked); completed++; warnings+=(results[name].warnings||[]).length; errors+=(results[name].errors||[]).length; updateProgress(elements,{current:name,completed,total:collectors.length,warnings,errors}); await new Promise(requestAnimationFrame); } latestFingerprint=buildFingerprint({collectorResults:results,startedAt,endedAt:new Date(),debugMode:elements.debugToggle.checked,extensionArtifactObservation,interactionExperiment}); renderFingerprint(latestFingerprint,elements,{search:elements.searchInput.value,filter:elements.filterSelect.value,changedPaths}); isCollecting=false; elements.collectButton.disabled=false; elements.recollectButton.disabled=false; maybeCompare(); }
async function runCollector(name,collector,debugMode){ const start=performance.now(); try{ const result=await withTimeout(Promise.resolve().then(collector),10000,name); return {...result,durationMs:Math.round(performance.now()-start)}; }catch(error){ return {category:name,supported:false,values:{},warnings:[],errors:[{collector:name,message:error.message||String(error),type:error.name||'CollectorError',stage:error.name==='TimeoutError'?'timeout':'collection',continued:true,stack:debugMode?error.stack:undefined}],durationMs:Math.round(performance.now()-start),timedOut:error.name==='TimeoutError'}; } }
function withTimeout(promise,ms,name){ return new Promise((resolve,reject)=>{ const id=setTimeout(()=>{const e=new Error(`${name} collector timed out after ${ms} ms`); e.name='TimeoutError'; reject(e);},ms); promise.then((v)=>{clearTimeout(id);resolve(v);},(e)=>{clearTimeout(id);reject(e);}); }); }
function maybeCompare(){ if(!latestFingerprint||!importedFingerprint) return; latestComparison=compareFingerprints(latestFingerprint, importedFingerprint,{includeVolatile:elements.includeVolatile.checked}); changedPaths=new Set(latestComparison.rows.filter(r=>['changed','only in current','only in imported'].includes(r.result)).map(r=>r.path)); renderComparison(latestComparison,elements,{showIdentical:elements.showIdentical.checked,onlyDifferences:elements.onlyDifferences.checked}); renderFilteredRows(latestFingerprint,elements,{search:elements.searchInput.value,filter:elements.filterSelect.value,changedPaths}); }

async function observeArtifacts(){
  elements.observeArtifactsButton.disabled=true; elements.artifactStatus.textContent='Observation Running'; elements.artifactDisconnected.textContent='No'; elements.artifactProgress.max=DEFAULT_EXTENSION_ARTIFACT_DURATION_MS;
  const started=performance.now(); const interval=setInterval(()=>{const elapsed=Math.min(DEFAULT_EXTENSION_ARTIFACT_DURATION_MS,performance.now()-started);elements.artifactProgress.value=elapsed;elements.artifactRemaining.textContent=`${Math.max(0,Math.ceil(DEFAULT_EXTENSION_ARTIFACT_DURATION_MS-elapsed))} ms remaining`;},50);
  const result=await observeAccessibilityExtensionArtifacts({ignoredRoot:elements.artifactPanel}); clearInterval(interval); const v=result.values;
  extensionArtifactObservation={performed:result.supported,observationStartedAt:v.observationStartedAt,observationFinishedAt:v.observationFinishedAt,observationDurationMs:v.observationDurationMs,configuredDurationMs:v.configuredDurationMs,observerDisconnected:v.observerDisconnected,aggregateFeatures:v};
  elements.artifactProgress.value=DEFAULT_EXTENSION_ARTIFACT_DURATION_MS; elements.artifactStatus.textContent='Observation Completed'; elements.artifactRemaining.textContent='0 ms remaining'; elements.artifactDuration.textContent=`${v.observationDurationMs} ms`; elements.artifactMutations.textContent=v.mutations.totalMutationCount; elements.artifactAria.textContent=v.accessibilityMutations.ariaMutationCount;
  elements.artifactInjected.textContent=v.injectedElements.styleElementCount+v.injectedElements.scriptElementCount+v.injectedElements.stylesheetLinkCount; elements.artifactGlobals.textContent=v.globalSurface.newGlobalPropertyNames.length; elements.artifactDisconnected.textContent=v.observerDisconnected?'Yes':'No'; elements.observeArtifactsButton.disabled=false;
  if(latestFingerprint){latestFingerprint={...latestFingerprint,extensionArtifactObservation};renderFingerprint(latestFingerprint,elements,{search:elements.searchInput.value,filter:elements.filterSelect.value,changedPaths});maybeCompare();}
}
elements.observeArtifactsButton.addEventListener('click',observeArtifacts);

elements.collectButton.addEventListener('click',collectFingerprint); elements.recollectButton.addEventListener('click',collectFingerprint); elements.clearButton.addEventListener('click',()=>{latestFingerprint=null; extensionArtifactObservation=null; elements.artifactStatus.textContent='Not Observed'; elements.artifactProgress.value=0; elements.artifactRemaining.textContent='Not running'; elements.artifactDuration.textContent='—'; elements.artifactMutations.textContent='—'; elements.artifactAria.textContent='—'; elements.artifactInjected.textContent='—'; elements.artifactGlobals.textContent='—'; elements.artifactDisconnected.textContent='No'; elements.structuredView.textContent='No fingerprint has been collected yet.'; elements.jsonViewer.textContent='{}'; elements.summaryCards.innerHTML=''; [elements.copyButton,elements.copySummaryButton,elements.downloadButton,elements.downloadSummaryButton].forEach(b=>b.disabled=true); renderStatus('Current result cleared.',elements);});
elements.copyButton.addEventListener('click',()=>action(()=>copyFingerprintJson(latestFingerprint),'Copied JSON.')); elements.copySummaryButton.addEventListener('click',()=>action(()=>copySummary(latestFingerprint),'Copied summary.')); elements.downloadButton.addEventListener('click',()=>latestFingerprint&&downloadFingerprintJson(latestFingerprint)); elements.downloadSummaryButton.addEventListener('click',()=>latestFingerprint&&downloadFingerprintJson(latestFingerprint,'summary'));
elements.importInput.addEventListener('change',async(e)=>{ const file=e.target.files?.[0]; if(!file) return; try{ importedFilename=file.name; importedFingerprint=JSON.parse(await file.text()); validateFingerprintJson(importedFingerprint); renderStatus(`Imported ${file.name} locally for comparison.`,elements); maybeCompare(); }catch(err){ importedFingerprint=null; renderStatus(`Import failed: ${err.message}`,elements); }});
[elements.includeVolatile,elements.showIdentical,elements.onlyDifferences].forEach(el=>el.addEventListener('change',maybeCompare)); elements.downloadComparisonButton.addEventListener('click',()=>{ if(latestComparison) downloadJson(createComparisonReport(latestComparison,{current:'current fingerprint',imported:importedFilename}),`comparison-report_${new Date().toISOString()}.json`,'comparison'); });
[elements.searchInput,elements.filterSelect].forEach(el=>el.addEventListener('input',()=>latestFingerprint&&renderFilteredRows(latestFingerprint,elements,{search:elements.searchInput.value,filter:elements.filterSelect.value,changedPaths}))); elements.clearFilters.addEventListener('click',()=>{elements.searchInput.value='';elements.filterSelect.value='all'; if(latestFingerprint) renderFilteredRows(latestFingerprint,elements,{changedPaths});});
elements.structuredToggle.addEventListener('click',()=>{elements.structuredView.hidden=false;elements.jsonViewer.hidden=true;}); elements.rawToggle.addEventListener('click',()=>{elements.structuredView.hidden=true;elements.jsonViewer.hidden=false;});
async function action(fn,msg){ try{ await fn(); elements.copyFeedback.textContent=msg; }catch(e){ elements.copyFeedback.textContent=`Action failed: ${e.message}`; } }

initializeExperimentPanel(document.querySelector('#interaction-experiment-panel'),{onResult(result){interactionExperiment=result;if(latestFingerprint){latestFingerprint={...latestFingerprint,interactionExperiment:result};renderFingerprint(latestFingerprint,elements,{search:elements.searchInput.value,filter:elements.filterSelect.value,changedPaths});maybeCompare();}}});
