import {InteractionRecorder} from '../experiments/interactionRecorder.js';import {createTaskStates} from '../experiments/experimentTasks.js';import {extractInteractionFeatures} from '../experiments/interactionFeatures.js';
export const EXPERIMENT_STATES=Object.freeze({IDLE:'IDLE',READY:'READY',RECORDING:'RECORDING',FINISHED:'FINISHED',CANCELLED:'CANCELLED'});
const allowed={assistiveTechnologyCondition:['unknown','no-screen-reader','screen-reader','keyboard-only','pointer-only','other-assistive-technology'],screenReader:['none','NVDA','JAWS','Narrator','VoiceOver','TalkBack','Orca','other','undisclosed'],deviceClass:['desktop','laptop','smartphone','tablet','XR-headset','unknown']};
export class ExperimentManager{
 constructor({recorder=new InteractionRecorder(),clock=()=>new Date()}={}){this.recorder=recorder;this.clock=clock;this.state=EXPERIMENT_STATES.IDLE;this.result={performed:false};this.tasks=[];this.currentTaskIndex=-1;}
 prepareExperiment(config={}){if(this.state===EXPERIMENT_STATES.RECORDING)throw new Error('An experiment is already recording');if(config.confirmed!==true)throw new Error('Participant notice confirmation is required');for(const k of Object.keys(allowed))if(!allowed[k].includes(config[k]))throw new Error(`Invalid ${k}`);this.groundTruth={assistiveTechnologyCondition:config.assistiveTechnologyCondition,screenReader:config.screenReader,deviceClass:config.deviceClass,browserConditionLabel:String(config.browserConditionLabel||''),participantCode:String(config.participantCode||''),trialNumber:numberOrNull(config.trialNumber),sessionNumber:numberOrNull(config.sessionNumber),notes:String(config.notes||'')};this.rawEventExportEnabled=config.rawEventExportEnabled===true;this.tasks=createTaskStates();this.currentTaskIndex=-1;this.result={performed:false};this.recorder.prepare();this.state=EXPERIMENT_STATES.READY;return this.snapshot();}
 startExperiment(){if(this.state!==EXPERIMENT_STATES.READY)throw new Error('Experiment must be ready');this.recorder.startRecording();this.state=EXPERIMENT_STATES.RECORDING;this.startTask(this.tasks[0].taskId);return this.snapshot();}
 startTask(taskId){if(this.state!==EXPERIMENT_STATES.RECORDING)throw new Error('Experiment is not recording');const i=this.tasks.findIndex(t=>t.taskId===taskId);if(i<0)throw new Error('Unknown task');if(this.currentTaskIndex>=0&&!this.tasks[this.currentTaskIndex].completed)throw new Error('Complete the current task first');this.currentTaskIndex=i;const t=this.tasks[i];t.startedAt=this.clock().toISOString();t._startTick=Date.now();this.recorder.setCurrentTask(taskId);return t;}
 completeTask(taskId=this.tasks[this.currentTaskIndex]?.taskId){if(this.state!==EXPERIMENT_STATES.RECORDING)throw new Error('Experiment is not recording');const t=this.tasks.find(x=>x.taskId===taskId);if(!t||!t.startedAt)throw new Error('Task is not active');t.finishedAt=this.clock().toISOString();t.durationMs=Math.max(0,Date.parse(t.finishedAt)-Date.parse(t.startedAt));t.completed=true;t.interactionCount=this.recorder.events.filter(e=>e.taskId===taskId).length;return t;}
 advanceTask(){const current=this.tasks[this.currentTaskIndex];if(!current?.completed)this.completeTask();if(this.currentTaskIndex===this.tasks.length-1)return null;return this.startTask(this.tasks[this.currentTaskIndex+1].taskId);}
 finishExperiment(){if(this.state!==EXPERIMENT_STATES.RECORDING)throw new Error('Experiment is not recording');const current=this.tasks[this.currentTaskIndex];if(current?.startedAt&&!current.completed)this.completeTask();const recording=this.recorder.finishRecording();const tasks=this.tasks.map(({_startTick,...t})=>({...t}));const aggregateFeatures=extractInteractionFeatures({events:recording.events,tasks,durationMs:recording.durationMs});this.result={performed:true,groundTruth:{...this.groundTruth},state:'finished',timing:{startedAt:recording.startedAt,finishedAt:recording.finishedAt,durationMs:recording.durationMs},tasks,aggregateFeatures,rawEventsIncluded:this.rawEventExportEnabled};if(this.rawEventExportEnabled)this.result.rawEvents=recording.events;this.state=EXPERIMENT_STATES.FINISHED;return structuredCloneSafe(this.result);}
 cancelExperiment(){this.recorder.removeAllListeners();this.recorder.reset();this.state=EXPERIMENT_STATES.CANCELLED;this.result={performed:false,state:'cancelled'};return this.result;}
 resetExperiment({preserveMetadata=true}={}){const metadata=preserveMetadata?this.groundTruth:null;this.recorder.reset();this.tasks=[];this.currentTaskIndex=-1;this.result={performed:false};this.state=EXPERIMENT_STATES.IDLE;if(!metadata)this.groundTruth=null;return this.snapshot();}
 snapshot(){return structuredCloneSafe({state:this.state,currentTaskIndex:this.currentTaskIndex,tasks:this.tasks,result:this.result,groundTruth:this.groundTruth});}
}
function numberOrNull(v){return v===''||v==null?null:Number(v);}function structuredCloneSafe(v){return JSON.parse(JSON.stringify(v));}
