import assert from 'node:assert/strict';
import { buildFingerprint, refreshDerivedRecord, SCHEMA_VERSION, APPLICATION_VERSION } from '../js/ui/summary.js';
import { EXPORT_TYPES, selectExport, fingerprintFilename, prepareExport } from '../js/export/jsonExport.js';
import { compareFingerprints } from '../js/ui/comparison.js';
const collectorResults={navigator:{supported:true,values:{userAgent:'test'},warnings:[],errors:[]},canvas:{supported:true,values:{hash:'x'},warnings:[],errors:[]},webxr:{supported:false,values:{available:false},warnings:['unsupported'],errors:[]},accessibilityPreferences:{supported:true,values:{reducedMotion:false},warnings:[],errors:[]},accessibilityEnvironment:{supported:true,values:{focus:'body'},warnings:[],errors:[]},accessibilityAPISurface:{supported:true,values:{ariaReflection:true},warnings:[],errors:[]}};
const record=buildFingerprint({collectorResults,startedAt:new Date('2026-01-01T00:00:00Z'),endedAt:new Date('2026-01-01T00:00:02Z')});
assert.equal(SCHEMA_VERSION,'2.0.0'); assert.equal(APPLICATION_VERSION,'1.2.0');
assert.equal(record.passiveSnapshot.performed,true); assert.equal(record.extensionArtifactObservation.performed,false); assert.equal(record.interactionExperiment.rawEventsIncluded,false);
assert.equal(record.accessibilitySummary.screenReaderDetectionModelStatus,'not-trained'); assert.equal(record.accessibilitySummary.classification,null);
assert.doesNotThrow(()=>JSON.parse(JSON.stringify(record)));
for(const type of EXPORT_TYPES.filter(x=>x!=='comparison')) assert.doesNotThrow(()=>JSON.parse(prepareExport(selectExport(record,type))));
assert.match(fingerprintFilename(record),/^xr-web-study_/);
const completed=refreshDerivedRecord({...record,interactionExperiment:{performed:true,groundTruth:{participantCode:'P001'},timing:{durationMs:4500},tasks:[],aggregateFeatures:{timing:{totalExperimentDuration:4500}},rawEventsIncluded:false}});
assert.equal(completed.featureGroups.interactionFeatures.timing.totalExperimentDuration,4500);
const other=structuredClone(completed);other.featureGroups.interactionFeatures.timing.totalExperimentDuration=5000;other.metadata.collectionId='other';
let comparison=compareFingerprints(completed,other,{family:'interactionFeatures'});
assert.equal(comparison.comparisonMode,'behavioral features');assert.ok(comparison.rows.some(r=>r.path.endsWith('totalExperimentDuration')&&r.result==='changed'&&!r.excluded));
comparison=compareFingerprints(completed,other,{family:'xrFeatures'});assert.equal(comparison.summary.changed,0);
console.log('Phase D integration tests passed');
