import {ExperimentManager,EXPERIMENT_STATES} from '../core/experimentManager.js';import {renderExperimentTaskEnvironment} from '../experiments/experimentTasks.js';
export function initializeExperimentPanel(root,{onResult=()=>{},onState=()=>{}}={}){const manager=new ExperimentManager();const q=s=>root.querySelector(s),form=q('#experiment-config'),start=q('#experiment-start'),confirm=q('#experiment-confirm'),status=q('#experiment-status'),running=q('#experiment-running'),finished=q('#experiment-finished'),environment=q('#experiment-environment-host');let elapsedTimer=null;
 confirm.addEventListener('change',()=>start.disabled=!confirm.checked);
 start.addEventListener('click',()=>{const data=new FormData(form);manager.prepareExperiment({...Object.fromEntries(data),confirmed:confirm.checked});manager.startExperiment();onState('Running');form.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);start.disabled=true;running.hidden=false;finished.hidden=true;environment.hidden=false;renderExperimentTaskEnvironment(environment);update();elapsedTimer=setInterval(update,500);});
 q('#experiment-complete-task').addEventListener('click',()=>{manager.completeTask();if(manager.currentTaskIndex===manager.tasks.length-1)finish();else update();});q('#experiment-next-task').addEventListener('click',()=>{manager.advanceTask();update();});q('#experiment-finish').addEventListener('click',finish);q('#experiment-cancel').addEventListener('click',()=>{const result=manager.cancelExperiment();cleanup();onState('Not Performed');onResult(result);status.textContent='Experiment Cancelled — recording stopped.';});q('#experiment-reset').addEventListener('click',()=>{manager.resetExperiment();cleanup();onState('Not Performed');confirm.checked=false;form.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=false);start.disabled=true;finished.hidden=true;status.textContent='Not started. Interaction listeners are inactive.';});
 function finish(){const result=manager.finishExperiment();cleanup();finished.hidden=false;q('#experiment-total').textContent=`${result.timing.durationMs} ms`;q('#experiment-completed-count').textContent=`${result.tasks.filter(t=>t.completed).length} of ${result.tasks.length}`;status.textContent='Experiment Completed — Recording Stopped';onState('Completed');onResult(result);}
 function cleanup(hide=true){clearInterval(elapsedTimer);elapsedTimer=null;running.hidden=hide;environment.hidden=hide;}
 function update(){if(manager.state!==EXPERIMENT_STATES.RECORDING)return;const t=manager.tasks[manager.currentTaskIndex],done=manager.tasks.filter(x=>x.completed).length;q('#experiment-task-position').textContent=`${manager.currentTaskIndex+1} of ${manager.tasks.length}`;q('#experiment-task-title').textContent=t.title;q('#experiment-task-instructions').textContent=t.instructions;q('#experiment-elapsed').textContent=`${Math.round((performance.now()-manager.recorder.startTick)/1000)} seconds`;q('#experiment-running-completed').textContent=done;q('#experiment-next-task').disabled=!t.completed||manager.currentTaskIndex===manager.tasks.length-1;q('#experiment-complete-task').disabled=t.completed;status.textContent='Experiment Running';}
 return manager;}
