import {ExperimentManager,EXPERIMENT_STATES} from '../core/experimentManager.js';import {renderExperimentTaskEnvironment} from '../experiments/experimentTasks.js';
export function initializeExperimentPanel(root,{onResult=()=>{},onState=()=>{}}={}){const manager=new ExperimentManager();const q=s=>root.querySelector(s),form=q('#experiment-config'),start=q('#experiment-start'),confirm=q('#experiment-confirm'),status=q('#experiment-status'),running=q('#experiment-running'),finished=q('#experiment-finished'),environment=q('#experiment-environment-host'),end=q('#experiment-end-controls');let elapsedTimer=null;confirm.addEventListener('change',()=>start.disabled=!confirm.checked);
 start.addEventListener('click',()=>{const area=renderExperimentTaskEnvironment(environment);environment.hidden=false;manager.recorder.setTaskArea(area);const data=new FormData(form);manager.prepareExperiment({...Object.fromEntries(data),confirmed:confirm.checked});manager.startExperiment();onState('Running');form.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);start.disabled=true;running.hidden=false;finished.hidden=true;end.hidden=true;update();elapsedTimer=setInterval(update,500);});
 q('#experiment-complete-task').addEventListener('click',()=>{manager.completeTask();if(manager.currentTaskIndex<manager.tasks.length-1)manager.advanceTask();update();focusCurrentStep();});q('#experiment-next-task').addEventListener('click',()=>{manager.advanceTask();update();focusCurrentStep();});q('#experiment-finish-bottom').addEventListener('click',finish);q('#experiment-cancel').addEventListener('click',()=>{const result=manager.cancelExperiment();cleanup();onState('Not Performed');onResult(result);status.textContent='Experiment Cancelled — recording stopped.';});q('#experiment-reset').addEventListener('click',()=>{manager.resetExperiment();cleanup();onState('Not Performed');confirm.checked=false;form.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=false);start.disabled=true;finished.hidden=true;end.hidden=true;q('#experiment-finish-bottom').disabled=true;status.textContent='Not started. Interaction listeners are inactive.';});
 function finish(){const result=manager.finishExperiment();cleanup();finished.hidden=false;q('#experiment-total').textContent=`${result.timing.durationMs} ms`;q('#experiment-completed-count').textContent=`${result.tasks.filter(t=>t.completed).length} of ${result.tasks.length}`;status.textContent='Experiment Completed — Recording Stopped';renderCondition(result.groundTruth);onState('Completed');onResult(result);}
 function renderCondition(g){q('#experiment-condition-summary').innerHTML=`<dt>Participant</dt><dd>${safe(g.participantCode||'participant-unknown')}</dd><dt>Device</dt><dd>${safe(g.deviceClass)}</dd><dt>Condition</dt><dd>${safe(g.assistiveTechnologyCondition)}</dd><dt>Screen Reader</dt><dd>${safe(g.screenReader)}</dd><dt>Trial</dt><dd>${safe(g.trialNumber??'—')}</dd><dt>Session</dt><dd>${safe(g.sessionNumber??'—')}</dd>`;}
 function cleanup(hide=true){clearInterval(elapsedTimer);elapsedTimer=null;running.hidden=hide;environment.hidden=hide;end.hidden=true;}
 function focusCurrentStep(){const allComplete=manager.tasks.length>0&&manager.tasks.every(t=>t.completed);q(allComplete?'#experiment-end-heading':'#experiment-task-title').focus();}
 function update(){if(manager.state!==EXPERIMENT_STATES.RECORDING)return;const t=manager.tasks[manager.currentTaskIndex],done=manager.tasks.filter(x=>x.completed).length,allComplete=done===manager.tasks.length;q('#experiment-task-position').textContent=`${manager.currentTaskIndex+1} of ${manager.tasks.length}`;q('#experiment-task-title').textContent=t.title;q('#experiment-task-instructions').textContent=t.instructions;q('#experiment-elapsed').textContent=`${Math.round((performance.now()-manager.recorder.startTick)/1000)} seconds`;q('#experiment-running-completed').textContent=done;q('#experiment-next-task').disabled=!t.completed||manager.currentTaskIndex===manager.tasks.length-1;q('#experiment-complete-task').disabled=t.completed;end.hidden=!allComplete;q('#experiment-finish-bottom').disabled=!allComplete;q('#experiment-end-count').textContent=`Tasks completed: ${done} / ${manager.tasks.length}`;status.textContent=allComplete?'All standardized tasks complete. Finish Experiment is now available below the task area.':'Experiment Running';}return manager;}
function safe(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
